### ISSUE TITLE
Use plugin configuration, don't decorate seneca

### ISSUE THREAD

**Issue by paolochiodi** [senecajs/seneca-repl#19]
This would make code like this possible:

``` js
require('seneca')({
  tag: 'repl',
  log: 'silent',
  legacy: { logging: false },
  debug: {short_logs:true}
})
.use(repl)
.repl()
```

instead of

``` js
var seneca = require('seneca')({
  tag: 'repl',
  log: 'silent',
  legacy: { logging: false },
  debug: {short_logs:true}
})
.use(plugin)
.ready(function () {
  seneca.repl()
})
```

**Comment by rjrodger** [comment]
seneca.repl should be deprecated, the repl functionality should be purely by plugin, so no need for decoration

**Comment by paolochiodi** [comment]
Changed title and scope of the issue: as @rjrodger is suggesting settings should be provided via the plugin options. The seneca main object decoration should then be avoided.

See https://github.com/senecajs/ramanujan/pull/8/files/bae67cdc4aba2a79df8d484b463792daf91f4e1f#r77996782

**Comment by rjrodger** [comment]
no longer relevant
