### ISSUE TITLE
Npm readme is not updated

### ISSUE THREAD

**Issue by Paker30** [senecajs/seneca-repl#27]
The readme which is published at npm is not accurate, the example you provide is from an old version

```js
var Seneca = require('seneca')
 
var seneca = Seneca()
  // open repl on default port 30303
  .use('seneca-repl')
```

This example is not valid anymore, the example is provided at github on the other hand is the one that works

```js
var Seneca = require('seneca')

var seneca = Seneca()
  // open repl on default port 30303
  .use('repl') 
```

It's not a big issue but it's a pitty a great documentation does not work because of an outdated example.

Regards.

**Comment by rjrodger** [comment]
seems to be updated now - not sure what way npm decides to do this
